---
language: java
sudo: false

jdk:
  - openjdk8

before_deploy:
  - "zip -r tracks.zip tracks/*"
  - "cd client ; ant compile ; cd .."
  - "cd server ; ant compile ; cd .."
  - "cd editor ; ant compile ; cd .."

jobs:
  include:
    - stage: compile
      name: "Client"
      script: "cd client ; ant compile"
    - name: "Server"
      script: "cd server ; ant compile"
    - name: "Editor"
      script: "cd editor ; ant compile"
    - stage: release
      deploy:
        script: "date"
        provider: releases
        api_key: $GitHub_Token
        file:
          - "server/server.jar"
          - "client/client.jar"
          - "editor/editor.jar"
          - "tracks.zip"
        skip_cleanup: true
        on:
          tags: true
